# Generated by Django 4.2.24 on 2025-10-08 07:14

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_id",
                    models.CharField(
                        editable=False,
                        help_text="系統自動生成 / Auto-generated",
                        max_length=50,
                        unique=True,
                        verbose_name="付款編號 / Payment ID",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("Credit", "信用卡 / Credit Card"),
                            ("WebATM", "網路ATM / Web ATM"),
                            ("ATM", "ATM轉帳 / ATM Transfer"),
                            ("CVS", "超商代碼 / CVS Code Payment"),
                            ("BARCODE", "超商條碼 / CVS Barcode Payment"),
                            ("AndroidPay", "Android Pay"),
                            ("ApplePay", "Apple Pay"),
                            ("LinePay", "LINE Pay"),
                        ],
                        default="Credit",
                        max_length=20,
                        verbose_name="付款方式 / Payment Method",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待付款 / Pending"),
                            ("processing", "處理中 / Processing"),
                            ("paid", "已付款 / Paid"),
                            ("failed", "付款失敗 / Failed"),
                            ("cancelled", "已取消 / Cancelled"),
                            ("refunded", "已退款 / Refunded"),
                            ("partial_refund", "部分退款 / Partial Refund"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="付款狀態 / Payment Status",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="新台幣 (NT$) / New Taiwan Dollar",
                        max_digits=10,
                        verbose_name="付款金額 / Payment Amount",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="TWD",
                        help_text="貨幣代碼 / Currency Code",
                        max_length=3,
                        verbose_name="貨幣 / Currency",
                    ),
                ),
                (
                    "ecpay_merchant_trade_no",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name="ECPay商店交易編號 / ECPay Merchant Trade No",
                    ),
                ),
                (
                    "ecpay_trade_no",
                    models.CharField(
                        blank=True,
                        help_text="ECPay系統交易編號 / ECPay system transaction number",
                        max_length=20,
                        null=True,
                        verbose_name="ECPay交易編號 / ECPay Trade No",
                    ),
                ),
                (
                    "ecpay_payment_date",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="ECPay付款時間 / ECPay Payment Date",
                    ),
                ),
                (
                    "ecpay_payment_type",
                    models.CharField(
                        blank=True,
                        help_text="ECPay回傳的付款類型 / Payment type returned by ECPay",
                        max_length=50,
                        verbose_name="ECPay付款類型 / ECPay Payment Type",
                    ),
                ),
                (
                    "ecpay_payment_type_charge_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="ECPay收取的手續費 / Fee charged by ECPay",
                        max_digits=10,
                        verbose_name="ECPay手續費 / ECPay Charge Fee",
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True,
                        help_text="銀行或第三方支付交易編號 / Bank or third-party transaction ID",
                        max_length=100,
                        verbose_name="交易編號 / Transaction ID",
                    ),
                ),
                (
                    "auth_code",
                    models.CharField(
                        blank=True,
                        help_text="信用卡授權碼 / Credit card authorization code",
                        max_length=50,
                        verbose_name="授權碼 / Authorization Code",
                    ),
                ),
                (
                    "bank_code",
                    models.CharField(
                        blank=True,
                        help_text="ATM轉帳銀行代碼 / ATM transfer bank code",
                        max_length=10,
                        verbose_name="銀行代碼 / Bank Code",
                    ),
                ),
                (
                    "virtual_account",
                    models.CharField(
                        blank=True,
                        help_text="ATM轉帳虛擬帳號 / ATM transfer virtual account",
                        max_length=20,
                        verbose_name="虛擬帳號 / Virtual Account",
                    ),
                ),
                (
                    "payment_code",
                    models.CharField(
                        blank=True,
                        help_text="超商繳費代碼 / CVS payment code",
                        max_length=20,
                        verbose_name="繳費代碼 / Payment Code",
                    ),
                ),
                (
                    "barcode_1",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="條碼1 / Barcode 1"
                    ),
                ),
                (
                    "barcode_2",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="條碼2 / Barcode 2"
                    ),
                ),
                (
                    "barcode_3",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="條碼3 / Barcode 3"
                    ),
                ),
                (
                    "payment_deadline",
                    models.DateTimeField(
                        blank=True,
                        help_text="ATM或超商付款期限 / ATM or CVS payment deadline",
                        null=True,
                        verbose_name="付款期限 / Payment Deadline",
                    ),
                ),
                (
                    "refund_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="退款金額 / Refund Amount",
                    ),
                ),
                (
                    "refund_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="退款日期 / Refund Date"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="建立時間 / Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="更新時間 / Updated At"
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="付款完成時間 / Paid At"
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment",
                        to="orders.order",
                        verbose_name="訂單 / Order",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="使用者 / User",
                    ),
                ),
            ],
            options={
                "verbose_name": "付款記錄 / Payment",
                "verbose_name_plural": "付款記錄 / Payments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RefundRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "refund_id",
                    models.CharField(
                        editable=False,
                        max_length=50,
                        unique=True,
                        verbose_name="退款編號 / Refund ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="新台幣 (NT$) / New Taiwan Dollar",
                        max_digits=10,
                        verbose_name="退款金額 / Refund Amount",
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        help_text="退款申請原因 / Reason for refund request",
                        verbose_name="退款原因 / Refund Reason",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待處理 / Pending"),
                            ("processing", "處理中 / Processing"),
                            ("completed", "已完成 / Completed"),
                            ("failed", "失敗 / Failed"),
                            ("cancelled", "已取消 / Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="退款狀態 / Refund Status",
                    ),
                ),
                (
                    "ecpay_refund_no",
                    models.CharField(
                        blank=True,
                        help_text="ECPay系統退款編號 / ECPay system refund number",
                        max_length=50,
                        verbose_name="ECPay退款編號 / ECPay Refund No",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="建立時間 / Created At"
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="處理時間 / Processed At"
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refunds",
                        to="payments.payment",
                        verbose_name="付款記錄 / Payment",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_refunds",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="處理人 / Processed By",
                    ),
                ),
            ],
            options={
                "verbose_name": "退款記錄 / Refund Record",
                "verbose_name_plural": "退款記錄 / Refund Records",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["payment", "-created_at"],
                        name="payments_re_payment_8dd509_idx",
                    ),
                    models.Index(
                        fields=["status"], name="payments_re_status_29b51f_idx"
                    ),
                    models.Index(
                        fields=["-created_at"], name="payments_re_created_1764e3_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PaymentLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "log_type",
                    models.CharField(
                        choices=[
                            ("request", "請求 / Request"),
                            ("response", "回應 / Response"),
                            ("callback", "回調 / Callback"),
                            ("error", "錯誤 / Error"),
                            ("info", "資訊 / Info"),
                        ],
                        default="info",
                        max_length=20,
                        verbose_name="日誌類型 / Log Type",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="日誌訊息內容 / Log message content",
                        verbose_name="訊息 / Message",
                    ),
                ),
                (
                    "request_data",
                    models.JSONField(
                        blank=True,
                        help_text="發送給ECPay的資料 / Data sent to ECPay",
                        null=True,
                        verbose_name="請求資料 / Request Data",
                    ),
                ),
                (
                    "response_data",
                    models.JSONField(
                        blank=True,
                        help_text="ECPay回傳的資料 / Data returned from ECPay",
                        null=True,
                        verbose_name="回應資料 / Response Data",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="發起請求的IP地址 / IP address of the request",
                        null=True,
                        verbose_name="IP地址 / IP Address",
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True,
                        help_text="瀏覽器用戶代理字符串 / Browser user agent string",
                        verbose_name="用戶代理 / User Agent",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="建立時間 / Created At"
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="payments.payment",
                        verbose_name="付款記錄 / Payment",
                    ),
                ),
            ],
            options={
                "verbose_name": "付款日誌 / Payment Log",
                "verbose_name_plural": "付款日誌 / Payment Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["payment", "-created_at"],
                        name="payments_pa_payment_0292fb_idx",
                    ),
                    models.Index(
                        fields=["log_type", "-created_at"],
                        name="payments_pa_log_typ_acf6f0_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="payments_pa_created_8e7da2_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["-created_at"], name="payments_pa_created_3147e3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["payment_id"], name="payments_pa_payment_6c9e39_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["ecpay_merchant_trade_no"],
                name="payments_pa_ecpay_m_315c3a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["ecpay_trade_no"], name="payments_pa_ecpay_t_ba2812_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["status"], name="payments_pa_status_7ad4af_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["user", "-created_at"], name="payments_pa_user_id_7a85fd_idx"
            ),
        ),
    ]
