# Generated by Django 4.2.24 on 2025-10-04 08:44

import authentication.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="用於登入的電子郵件地址",
                        max_length=254,
                        unique=True,
                        verbose_name="電子郵件地址",
                    ),
                ),
                (
                    "preferred_language",
                    models.CharField(
                        choices=[("zh-hant", "繁體中文"), ("en", "English")],
                        default="zh-hant",
                        help_text="使用者介面和電子郵件的偏好語言",
                        max_length=10,
                        verbose_name="偏好語言",
                    ),
                ),
                (
                    "is_email_confirmed",
                    models.BooleanField(
                        default=False,
                        help_text="用戶是否已確認其電子郵件地址",
                        verbose_name="電子郵件已確認",
                    ),
                ),
                (
                    "pdpa_consent",
                    models.BooleanField(
                        default=False,
                        help_text="用戶是否同意個人資料保護法條款",
                        verbose_name="PDPA同意",
                    ),
                ),
                (
                    "pdpa_consent_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="用戶同意PDPA條款的日期和時間",
                        null=True,
                        verbose_name="PDPA同意日期",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="帳戶是否已啟用（需要電子郵件確認）",
                        verbose_name="帳戶啟用",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "用戶",
                "verbose_name_plural": "用戶",
            },
            managers=[
                ("objects", authentication.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name="UserPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("zh-hant", "繁體中文"), ("en", "English")],
                        default="zh-hant",
                        max_length=10,
                        verbose_name="語言",
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="Asia/Taipei",
                        help_text="用戶的時區設定",
                        max_length=50,
                        verbose_name="時區",
                    ),
                ),
                (
                    "email_notifications",
                    models.BooleanField(
                        default=True, help_text="是否接收電子郵件通知", verbose_name="電子郵件通知"
                    ),
                ),
                (
                    "marketing_emails",
                    models.BooleanField(
                        default=False, help_text="是否接收行銷電子郵件", verbose_name="行銷電子郵件"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="創建時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用戶",
                    ),
                ),
            ],
            options={
                "verbose_name": "用戶偏好設定",
                "verbose_name_plural": "用戶偏好設定",
            },
        ),
        migrations.CreateModel(
            name="LoginAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="嘗試登入的電子郵件地址", max_length=254, verbose_name="嘗試的電子郵件"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        help_text="發出登入嘗試的IP地址", verbose_name="IP地址"
                    ),
                ),
                (
                    "attempted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="嘗試時間"),
                ),
                (
                    "success",
                    models.BooleanField(
                        default=False, help_text="登入嘗試是否成功", verbose_name="成功"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True, help_text="發出請求的瀏覽器用戶代理字符串", verbose_name="用戶代理"
                    ),
                ),
            ],
            options={
                "verbose_name": "登入嘗試",
                "verbose_name_plural": "登入嘗試",
                "indexes": [
                    models.Index(
                        fields=["email", "attempted_at"],
                        name="authenticat_email_ce6fe3_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "attempted_at"],
                        name="authenticat_ip_addr_140591_idx",
                    ),
                    models.Index(
                        fields=["attempted_at"], name="authenticat_attempt_28e2fb_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PasswordResetToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        default=uuid.uuid4,
                        help_text="用於密碼重設的唯一令牌",
                        max_length=255,
                        unique=True,
                        verbose_name="重設令牌",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="創建時間"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(help_text="令牌過期的日期和時間", verbose_name="過期時間"),
                ),
                (
                    "is_used",
                    models.BooleanField(
                        default=False, help_text="令牌是否已被使用", verbose_name="已使用"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        help_text="發出重設請求的IP地址", verbose_name="IP地址"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_reset_tokens",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用戶",
                    ),
                ),
            ],
            options={
                "verbose_name": "密碼重設令牌",
                "verbose_name_plural": "密碼重設令牌",
                "indexes": [
                    models.Index(fields=["token"], name="authenticat_token_3288c7_idx"),
                    models.Index(
                        fields=["user", "is_used"],
                        name="authenticat_user_id_9751b1_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="authenticat_expires_8662be_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EmailConfirmationToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        default=uuid.uuid4,
                        help_text="用於電子郵件確認的唯一令牌",
                        max_length=255,
                        unique=True,
                        verbose_name="確認令牌",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="正在確認的電子郵件地址", max_length=254, verbose_name="確認的電子郵件"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="創建時間"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(help_text="令牌過期的日期和時間", verbose_name="過期時間"),
                ),
                (
                    "is_used",
                    models.BooleanField(
                        default=False, help_text="令牌是否已被使用", verbose_name="已使用"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_confirmation_tokens",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用戶",
                    ),
                ),
            ],
            options={
                "verbose_name": "電子郵件確認令牌",
                "verbose_name_plural": "電子郵件確認令牌",
                "indexes": [
                    models.Index(fields=["token"], name="authenticat_token_f611a0_idx"),
                    models.Index(
                        fields=["user", "is_used"],
                        name="authenticat_user_id_420d87_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="authenticat_expires_2ac78c_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(fields=["email"], name="authenticat_email_486e08_idx"),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(
                fields=["is_active", "is_email_confirmed"],
                name="authenticat_is_acti_e14820_idx",
            ),
        ),
    ]
