# Generated by Django 4.2.24 on 2025-10-04 08:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="訪客的會話標識",
                        max_length=40,
                        null=True,
                        verbose_name="會話金鑰",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="創建時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        help_text="購物車所有者（登入用戶）",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用戶",
                    ),
                ),
            ],
            options={
                "verbose_name": "購物車",
                "verbose_name_plural": "購物車",
            },
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="購買數量",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="數量",
                    ),
                ),
                (
                    "price_at_addition",
                    models.DecimalField(
                        decimal_places=0,
                        help_text="商品加入購物車時的價格",
                        max_digits=10,
                        verbose_name="加入時價格",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="加入時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="cart.cart",
                        verbose_name="購物車",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                        verbose_name="產品",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        help_text="產品變體（如有）",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.productvariant",
                        verbose_name="產品規格",
                    ),
                ),
            ],
            options={
                "verbose_name": "購物車商品",
                "verbose_name_plural": "購物車商品",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["cart", "product"],
                        name="cart_cartit_cart_id_4bd8c3_idx",
                    )
                ],
                "unique_together": {("cart", "product", "variant")},
            },
        ),
        migrations.AddIndex(
            model_name="cart",
            index=models.Index(fields=["user"], name="cart_cart_user_id_b645f9_idx"),
        ),
        migrations.AddIndex(
            model_name="cart",
            index=models.Index(
                fields=["session_key"], name="cart_cart_session_5e1af5_idx"
            ),
        ),
    ]
