# Generated by Django 4.2.24 on 2025-10-07 02:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cart",
            options={
                "verbose_name": "購物車 / Shopping Cart",
                "verbose_name_plural": "購物車 / Shopping Carts",
            },
        ),
        migrations.AlterModelOptions(
            name="cartitem",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "購物車商品 / Cart Item",
                "verbose_name_plural": "購物車商品 / Cart Items",
            },
        ),
        migrations.AlterField(
            model_name="cart",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="創建時間 / Created At"
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="session_key",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="訪客的會話標識 / Guest session identifier",
                max_length=40,
                null=True,
                verbose_name="會話金鑰 / Session Key",
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新時間 / Updated At"),
        ),
        migrations.AlterField(
            model_name="cart",
            name="user",
            field=models.OneToOneField(
                blank=True,
                help_text="購物車所有者（登入用戶）/ Cart owner (authenticated user)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart",
                to=settings.AUTH_USER_MODEL,
                verbose_name="使用者 / User",
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="cart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="cart.cart",
                verbose_name="購物車 / Cart",
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="加入時間 / Added At"
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="price_at_addition",
            field=models.DecimalField(
                decimal_places=2,
                help_text="商品加入購物車時的價格 / Product price when added to cart",
                max_digits=10,
                verbose_name="加入時價格（新台幣）/ Price at Addition (NT$)",
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="products.product",
                verbose_name="產品 / Product",
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="quantity",
            field=models.PositiveIntegerField(
                default=1,
                help_text="購買數量 / Purchase quantity",
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="數量 / Quantity",
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新時間 / Updated At"),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                help_text="產品變體（如有）/ Product variant (if any)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.productvariant",
                verbose_name="產品規格 / Product Variant",
            ),
        ),
        migrations.AddIndex(
            model_name="cart",
            index=models.Index(
                fields=["-updated_at"], name="cart_cart_updated_758c74_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cartitem",
            index=models.Index(
                fields=["-created_at"], name="cart_cartit_created_10634c_idx"
            ),
        ),
    ]
