# Generated by Django 4.2.24 on 2025-10-08 07:32

from django.db import migrations
from decimal import Decimal


def fix_cart_item_prices(apps, schema_editor):
    """
    Fix cart items that have None prices by setting them from product prices.
    """
    CartItem = apps.get_model('cart', 'CartItem')
    
    # Find cart items with None prices
    items_with_none_prices = CartItem.objects.filter(price_at_addition__isnull=True)
    
    for item in items_with_none_prices:
        # Try to get price from variant first, then product
        price = None
        
        if item.variant and hasattr(item.variant, 'final_price') and item.variant.final_price:
            price = item.variant.final_price
        elif item.product:
            if item.product.sale_price:
                price = item.product.sale_price
            elif item.product.price:
                price = item.product.price
        
        # Set price or default to 0
        if price is not None:
            item.price_at_addition = price
        else:
            item.price_at_addition = Decimal('0.00')
        
        item.save()
        print(f"Fixed cart item {item.id}: set price to {item.price_at_addition}")


def reverse_fix_cart_item_prices(apps, schema_editor):
    """
    Reverse migration - no action needed.
    """
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0002_alter_cart_options_alter_cartitem_options_and_more"),
    ]

    operations = [
        migrations.RunPython(fix_cart_item_prices, reverse_fix_cart_item_prices),
    ]
