# Generated by Django 4.2.24 on 2025-10-04 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        editable=False,
                        help_text="系統自動生成 / Auto-generated",
                        max_length=50,
                        unique=True,
                        verbose_name="訂單編號 / Order Number",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待處理 / Pending"),
                            ("processing", "處理中 / Processing"),
                            ("shipped", "已出貨 / Shipped"),
                            ("delivered", "已送達 / Delivered"),
                            ("cancelled", "已取消 / Cancelled"),
                            ("refunded", "已退款 / Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="訂單狀態 / Order Status",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "待付款 / Pending"),
                            ("paid", "已付款 / Paid"),
                            ("failed", "付款失敗 / Failed"),
                            ("refunded", "已退款 / Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="付款狀態 / Payment Status",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("credit_card", "信用卡 / Credit Card"),
                            ("atm", "ATM 轉帳 / ATM Transfer"),
                            ("cvs_code", "超商代碼 / CVS Code"),
                            ("line_pay", "LINE Pay"),
                            ("apple_pay", "Apple Pay"),
                            ("google_pay", "Google Pay"),
                        ],
                        default="credit_card",
                        max_length=20,
                        verbose_name="付款方式 / Payment Method",
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="交易編號 / Transaction ID",
                    ),
                ),
                (
                    "shipping_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("home_delivery", "宅配 / Home Delivery"),
                            ("seven_eleven", "7-11 取貨 / 7-11 Pickup"),
                            ("family_mart", "全家取貨 / FamilyMart Pickup"),
                            ("hi_life", "萊爾富取貨 / Hi-Life Pickup"),
                            ("ok_mart", "OK超商取貨 / OK Mart Pickup"),
                        ],
                        default="home_delivery",
                        max_length=20,
                        verbose_name="配送方式 / Shipping Method",
                    ),
                ),
                (
                    "recipient_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="收件人姓名 / Recipient Name",
                    ),
                ),
                (
                    "recipient_phone",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=20,
                        verbose_name="收件人電話 / Recipient Phone",
                    ),
                ),
                (
                    "shipping_postal_code",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=10,
                        verbose_name="郵遞區號 / Postal Code",
                    ),
                ),
                (
                    "shipping_city",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="縣市 / City"
                    ),
                ),
                (
                    "shipping_district",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="區域 / District",
                    ),
                ),
                (
                    "shipping_address",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="詳細地址 / Detailed Address",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="商品小計 / Subtotal",
                    ),
                ),
                (
                    "shipping_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="運費 / Shipping Fee",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="總金額 / Total Amount",
                    ),
                ),
                (
                    "customer_notes",
                    models.TextField(blank=True, verbose_name="客戶備註 / Customer Notes"),
                ),
                (
                    "admin_notes",
                    models.TextField(blank=True, verbose_name="管理員備註 / Admin Notes"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="建立時間 / Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="更新時間 / Updated At"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="使用者 / User",
                    ),
                ),
            ],
            options={
                "verbose_name": "訂單 / Order",
                "verbose_name_plural": "訂單 / Orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ShippingAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recipient_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="收件人姓名 / Recipient Name",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="電話 / Phone"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=10,
                        verbose_name="郵遞區號 / Postal Code",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="縣市 / City"
                    ),
                ),
                (
                    "district",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="區域 / District",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="詳細地址 / Detailed Address",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="建立時間 / Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="更新時間 / Updated At"
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipping_address_detail",
                        to="orders.order",
                        verbose_name="訂單 / Order",
                    ),
                ),
            ],
            options={
                "verbose_name": "配送地址 / Shipping Address",
                "verbose_name_plural": "配送地址 / Shipping Addresses",
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="商品名稱 / Product Name",
                    ),
                ),
                (
                    "product_sku",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="商品編號 / SKU",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1, verbose_name="數量 / Quantity"
                    ),
                ),
                (
                    "price_at_purchase",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="新台幣 (NT$) / New Taiwan Dollar",
                        max_digits=10,
                        verbose_name="購買時價格 / Price at Purchase",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="建立時間 / Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="更新時間 / Updated At"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                        verbose_name="訂單 / Order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="products.product",
                        verbose_name="商品 / Product",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="products.productvariant",
                        verbose_name="規格 / Variant",
                    ),
                ),
            ],
            options={
                "verbose_name": "訂單項目 / Order Item",
                "verbose_name_plural": "訂單項目 / Order Items",
                "ordering": ["id"],
            },
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["-created_at"], name="orders_orde_created_f0ce29_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["order_number"], name="orders_orde_order_n_f3ada5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["user", "-created_at"], name="orders_orde_user_id_0ae59f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["status"], name="orders_orde_status_c6dd84_idx"),
        ),
    ]
