# Generated by Django 4.2.24 on 2025-10-04 08:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="產品分類名稱（繁體中文）/ Product category name (Traditional Chinese)",
                        max_length=200,
                        verbose_name="分類名稱 / Category Name",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True,
                        help_text="英文分類名稱 / English category name",
                        max_length=200,
                        verbose_name="分類名稱（英文）/ Category Name (English)",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="用於URL的唯一代碼 / Unique code for URLs",
                        max_length=200,
                        unique=True,
                        verbose_name="網址代碼 / URL Slug",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="分類描述（繁體中文）/ Category description (Traditional Chinese)",
                        verbose_name="描述 / Description",
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        blank=True,
                        help_text="英文分類描述 / English category description",
                        verbose_name="描述（英文）/ Description (English)",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="categories/",
                        verbose_name="分類圖片 / Category Image",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="是否顯示此分類 / Whether to display this category",
                        verbose_name="啟用 / Active",
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        default=0,
                        help_text="排序順序（數字越小越前面）/ Sort order (lower numbers appear first)",
                        verbose_name="顯示順序 / Display Order",
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        help_text="搜尋引擎顯示標題（繁體中文）/ Search engine title (Traditional Chinese)",
                        max_length=200,
                        verbose_name="SEO標題 / SEO Title",
                    ),
                ),
                (
                    "meta_title_en",
                    models.CharField(
                        blank=True,
                        help_text="英文搜尋引擎標題 / English search engine title",
                        max_length=200,
                        verbose_name="SEO標題（英文）/ SEO Title (English)",
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True,
                        help_text="搜尋引擎顯示描述（繁體中文）/ Search engine description (Traditional Chinese)",
                        verbose_name="SEO描述 / SEO Description",
                    ),
                ),
                (
                    "meta_description_en",
                    models.TextField(
                        blank=True,
                        help_text="英文搜尋引擎描述 / English search engine description",
                        verbose_name="SEO描述（英文）/ SEO Description (English)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="創建時間 / Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="更新時間 / Updated At"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="父分類（如果有）/ Parent category (if any)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="products.category",
                        verbose_name="上層分類 / Parent Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "產品分類 / Product Category",
                "verbose_name_plural": "產品分類 / Product Categories",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="產品名稱（繁體中文）/ Product name (Traditional Chinese)",
                        max_length=300,
                        verbose_name="產品名稱 / Product Name",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True,
                        help_text="英文產品名稱 / English product name",
                        max_length=300,
                        verbose_name="產品名稱（英文）/ Product Name (English)",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="用於URL的唯一代碼 / Unique code for URLs",
                        max_length=300,
                        unique=True,
                        verbose_name="網址代碼 / URL Slug",
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        help_text="庫存單位編號 / Stock Keeping Unit",
                        max_length=100,
                        unique=True,
                        verbose_name="產品編號 / SKU",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="詳細產品描述（繁體中文）/ Detailed product description (Traditional Chinese)",
                        verbose_name="產品描述 / Product Description",
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        blank=True,
                        help_text="英文產品描述 / English product description",
                        verbose_name="產品描述（英文）/ Product Description (English)",
                    ),
                ),
                (
                    "specifications",
                    models.TextField(
                        blank=True,
                        help_text="技術規格（繁體中文）/ Technical specifications (Traditional Chinese)",
                        verbose_name="產品規格 / Specifications",
                    ),
                ),
                (
                    "specifications_en",
                    models.TextField(
                        blank=True,
                        help_text="英文技術規格 / English technical specifications",
                        verbose_name="產品規格（英文）/ Specifications (English)",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="新台幣售價 / Price in New Taiwan Dollar",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="售價（新台幣）/ Price (NT$)",
                    ),
                ),
                (
                    "sale_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="促銷價格（如果有）/ Promotional price (if any)",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="特價（新台幣）/ Sale Price (NT$)",
                    ),
                ),
                (
                    "cost_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="進貨成本（內部使用）/ Purchase cost (internal use)",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="成本價（新台幣）/ Cost Price (NT$)",
                    ),
                ),
                (
                    "stock",
                    models.IntegerField(
                        default=0,
                        help_text="現有庫存數量 / Current stock quantity",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="庫存數量 / Stock Quantity",
                    ),
                ),
                (
                    "low_stock_threshold",
                    models.IntegerField(
                        default=10,
                        help_text="低於此數量時顯示警告 / Show warning when below this quantity",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="低庫存警示 / Low Stock Threshold",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿 / Draft"),
                            ("active", "上架中 / Active"),
                            ("out_of_stock", "缺貨 / Out of Stock"),
                            ("discontinued", "停售 / Discontinued"),
                        ],
                        default="draft",
                        help_text="產品狀態 / Product status",
                        max_length=20,
                        verbose_name="狀態 / Status",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="是否顯示在首頁精選區 / Display in homepage featured section",
                        verbose_name="精選產品 / Featured Product",
                    ),
                ),
                (
                    "is_new",
                    models.BooleanField(
                        default=False,
                        help_text="是否標示為新品 / Mark as new arrival",
                        verbose_name="新品 / New Arrival",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="產品重量（用於運費計算）/ Product weight (for shipping calculation)",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="重量（公克）/ Weight (grams)",
                    ),
                ),
                (
                    "dimensions",
                    models.CharField(
                        blank=True,
                        help_text="產品尺寸（長x寬x高 cm）/ Product dimensions (L x W x H cm)",
                        max_length=100,
                        verbose_name="尺寸 / Dimensions",
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        help_text="搜尋引擎顯示標題（繁體中文）/ Search engine title (Traditional Chinese)",
                        max_length=200,
                        verbose_name="SEO標題 / SEO Title",
                    ),
                ),
                (
                    "meta_title_en",
                    models.CharField(
                        blank=True,
                        help_text="英文搜尋引擎標題 / English search engine title",
                        max_length=200,
                        verbose_name="SEO標題（英文）/ SEO Title (English)",
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True,
                        help_text="搜尋引擎顯示描述（繁體中文）/ Search engine description (Traditional Chinese)",
                        verbose_name="SEO描述 / SEO Description",
                    ),
                ),
                (
                    "meta_description_en",
                    models.TextField(
                        blank=True,
                        help_text="英文搜尋引擎描述 / English search engine description",
                        verbose_name="SEO描述（英文）/ SEO Description (English)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="創建時間 / Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="更新時間 / Updated At"
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="產品上架日期時間 / Product publish date and time",
                        null=True,
                        verbose_name="上架時間 / Published At",
                    ),
                ),
                (
                    "view_count",
                    models.IntegerField(
                        default=0,
                        help_text="產品被瀏覽的次數 / Number of times product was viewed",
                        verbose_name="瀏覽次數 / View Count",
                    ),
                ),
                (
                    "sales_count",
                    models.IntegerField(
                        default=0,
                        help_text="已售出數量 / Number of units sold",
                        verbose_name="銷售數量 / Sales Count",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="products.category",
                        verbose_name="分類 / Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "產品 / Product",
                "verbose_name_plural": "產品 / Products",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="例如：紅色/L號/256GB / e.g., Red/L/256GB",
                        max_length=200,
                        verbose_name="規格名稱 / Variant Name",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True,
                        help_text="英文規格名稱 / English variant name",
                        max_length=200,
                        verbose_name="規格名稱（英文）/ Variant Name (English)",
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        help_text="規格專屬SKU / Unique SKU for this variant",
                        max_length=100,
                        unique=True,
                        verbose_name="規格編號 / Variant SKU",
                    ),
                ),
                (
                    "price_difference",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="相對於主產品的價格調整（可為負數）/ Price adjustment relative to main product (can be negative)",
                        max_digits=10,
                        verbose_name="價格差異（新台幣）/ Price Difference (NT$)",
                    ),
                ),
                (
                    "stock",
                    models.IntegerField(
                        default=0,
                        help_text="此規格的庫存數量 / Stock quantity for this variant",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="庫存數量 / Stock Quantity",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="是否可供選擇 / Whether this variant is available for selection",
                        verbose_name="啟用 / Active",
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(default=0, verbose_name="顯示順序 / Display Order"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="創建時間 / Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="更新時間 / Updated At"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="products.product",
                        verbose_name="產品 / Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "產品規格 / Product Variant",
                "verbose_name_plural": "產品規格 / Product Variants",
                "ordering": ["display_order", "name"],
                "indexes": [
                    models.Index(fields=["sku"], name="products_pr_sku_dcab68_idx"),
                    models.Index(
                        fields=["product", "is_active"],
                        name="products_pr_product_66459e_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="產品圖片 / Product image",
                        upload_to="products/%Y/%m/",
                        verbose_name="圖片 / Image",
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        help_text="圖片替代文字（繁體中文，用於SEO）/ Image alt text (Traditional Chinese, for SEO)",
                        max_length=200,
                        verbose_name="替代文字 / Alt Text",
                    ),
                ),
                (
                    "alt_text_en",
                    models.CharField(
                        blank=True,
                        help_text="英文圖片替代文字（用於SEO）/ English image alt text (for SEO)",
                        max_length=200,
                        verbose_name="替代文字（英文）/ Alt Text (English)",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="是否為主要顯示圖片 / Whether this is the primary display image",
                        verbose_name="主要圖片 / Primary Image",
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        default=0,
                        help_text="排序順序 / Sort order",
                        verbose_name="顯示順序 / Display Order",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="上傳時間 / Uploaded At"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="products.product",
                        verbose_name="產品 / Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "產品圖片 / Product Image",
                "verbose_name_plural": "產品圖片 / Product Images",
                "ordering": ["display_order", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["product", "is_primary"],
                        name="products_pr_product_1b7905_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["slug"], name="products_pr_slug_3edc0c_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["sku"], name="products_pr_sku_ca0cdc_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["status", "-created_at"], name="products_pr_status_8ee08e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["category", "status"], name="products_pr_categor_75eeb5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_featured", "status"], name="products_pr_is_feat_bd97b9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(fields=["slug"], name="products_ca_slug_da4386_idx"),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["is_active", "display_order"],
                name="products_ca_is_acti_9a0e2e_idx",
            ),
        ),
    ]
